### ISSUE TITLE
Modpack doesn't work without smoothboot?

### ISSUE THREAD

**Issue by Vinesauced** [AbdElAziz333/SmoothBoot-Reloaded#14]
I recently decided to switch from smoothboot to modernfix in my custom forge 1.19.2 modpack. and just disabling smoothboot is enough to cause `stack smashing` crash.  Trying to use modernfix instead doesn't change anything.
full log uploaded here: https://mclo.gs/3Rf2mMp
crash report: https://mclo.gs/FpTBgqI

**Comment by AbdElAziz333** [comment]
Remove Smooth Boot (Reloaded) and see if the issue still occur, if it is, please open a new issue.
