### ISSUE TITLE
Tinkers' Tools textures broken (1.18.2 Forge)

### ISSUE THREAD

**Issue by HeavyParaBeetle** [AbdElAziz333/SmoothBoot-Reloaded#16]
The way mixins multithreading was changed breaks the way Tinkers' tools modular textures work. All Modifier textures do not appear and all parts use their fallback plain colors.

Tinkers' Construct version: 3.6.4.133
Smooth Boot Reloaded version: 0.0.2

**Comment by AbdElAziz333** [comment]
Please test with only Smooth Boot (Reloaded) and Tinker's Construct, if the issue still happens, open a new issue.
