### ISSUE TITLE
Crash on load

### ISSUE THREAD

**Issue by DragonMaster14545** [AbdElAziz333/SmoothBoot-Reloaded#17]
Hello I am getting this crash Randomly. 
[crash-2023-07-23_09.56.16-fml.txt](https://github.com/AbdElAziz333/SmoothBoot-Reloaded/files/12138245/crash-2023-07-23_09.56.16-fml.txt)
When I restart the game, it loads normally. The mods that error also aren't always the same. I a not sure if this is your mod, but it is the only one that alters loading that I have insalled. Thanks in advance

**Comment by AbdElAziz333** [comment]
Please remove Smooth Boot (Reloaded) and see if the issue still occur, if it still, open a new issue.
