### ISSUE TITLE
[Question] Is there be a 1.20.x update planned?

### ISSUE THREAD

**Issue by kermitted** [AbdElAziz333/SmoothBoot-Reloaded#18]
Just wanted to ask if there were any plans to update this mod to 1.20.x? because it truly does help my game run so much better.

**Comment by RedGreenBlue09** [comment]
I have a fork that's updated to 1.19.4 and 1.20.1. Have been using it for months without issues.

https://github.com/RedGreenBlue09/SmoothBoot-Reloaded/releases

(I don't plan to publish it anywhere as I don't have permission and modding knowledge)

**Comment by RedGreenBlue09** [comment]
The mod is updated today, so this can be closed.
