### ISSUE TITLE
Inconsistent thread counts and priorities compared to upstream

### ISSUE THREAD

**Issue by input-Here** [AbdElAziz333/SmoothBoot-Reloaded#19]
This port still uses the 1.16 values for 1.18+ versions. Upstream uses the [`the number of available threads-1`](https://github.com/UltimateBoomer/mc-smoothboot/blob/1.19.4/src/main/java/io/github/ultimateboomer/smoothboot/config/SmoothBootConfig.java#L13) as the amount of main worker threads, while this port currently uses [`the number of available threads/2`](https://github.com/AbdElAziz333/SmoothBoot-Reloaded/blob/mc1.20.1/dev/src/main/java/com/abdelaziz/smoothboot/config/SmoothBootConfig.java#L7), resulting in worse performance. 
According to the [original wiki](https://github.com/UltimateBoomer/mc-smoothboot/wiki/Configuration~-Fabric-1.16+#thread-priority) (I am aware this is for fabric, but it's 1.16+ in general), it also appears that the thread priorities are different- using 5 and 3 instead of 5 and 1, however this doesn't seem to be reflected in the upstream code for some reason.

**Comment by AbdElAziz333** [comment]
Yes, i've made these changes but i didn't released it yet.

**Comment by AbdElAziz333** [comment]
Fixed in the new update.

**Comment by input-Here** [comment]
Awesome, thanks!
