### ISSUE TITLE
demand

### ISSUE THREAD

**Issue by 623667595** [AbdElAziz333/SmoothBoot-Reloaded#2]
Can I reset 1.12.2? There is source code in the original build station, but I can't build it successfully without some things. Help me, I hope I can experience smooth loading in 1.12.2

**Comment by AbdElAziz333** [comment]
I am a new modder for minecraft 1.16.5 amd up so i don't know about 1.12.2 mappings, and this version of smooth boot is for minecraft 1.18.2 and up.
