### ISSUE TITLE
[1.19.2]Mixin prepare failed preparing UtilMixin

### ISSUE THREAD

**Issue by OcrSu** [AbdElAziz333/SmoothBoot-Reloaded#3]
[debug-1.log](https://github.com/AbdElAziz333/SmoothBoot-Reloaded/files/9926764/debug-1.log)

**Comment by AbdElAziz333** [comment]
how to reproduction?

**Comment by OcrSu** [comment]
This happens in my modpack, but it's not fully developed yet.
when the first preview version is complete, I'll test it and link the results and modpack here.

> how to reproduction?

**Comment by OcrSu** [comment]
It seems that the problem has disappeared. The crash may be an accident
