### ISSUE TITLE
[Question] This comes at the cost of load times, right?

### ISSUE THREAD

**Issue by StormDragon-64** [AbdElAziz333/SmoothBoot-Reloaded#4]
Basically the title, but I have another question: does the answer change if I have lazy dfu installed?

**Comment by AbdElAziz333** [comment]
sure, but there other info you should know, smooth boot (reloaded) by its default configuration its makes the game smoother while increasing loading time speed, but you can change the configuration about your weldments, increasing threads count and priority will improve the loading time speed, for more info about the configuration file, press [here](https://github.com/AbdElAziz333/SmoothBoot-Reloaded/wiki/Configuration-File).

I hope you have a good day!
