### ISSUE TITLE
Tinkers' Construct Incompatibility

### ISSUE THREAD

**Issue by Mnaq** [AbdElAziz333/SmoothBoot-Reloaded#8]
All tools' texture from [Tinkers' Construct](https://www.curseforge.com/minecraft/mc-mods/tinkers-construct) is white.
There is a way to fix it by reloading textures (F3 + T), but I don't really want to reload textures every time I play.

**Comment by AbdElAziz333** [comment]
Please try remove any unofficial Sodium mod fork for forge and try again, Smooth Boot (Reloaded) doesn't change any behavior in the game mechanics.

**Comment by AbdElAziz333** [comment]
This is not Smooth Boot (Reloaded) issue.
